#!/bin/bash

declare -A fator
fator[1]=1
fator[2]=0.55
fator[3]=0.41
fator[4]=0.33
fator[5]=0.28
fator[6]=0.25
fator[7]=0.23
fator[8]=0.21

if [[ ${#} != 3 || ! ${1} =~ ^[0-9\.]{3,4}$ || ! ${2} =~ ^[0-9]{1}$ || ! ${3} =~ ^[0-9]{1,4}$ ]]; then
        echo "Use: ${0} LEECH_PERCENT MONSTERS_QUANTID SPELL_DAMAGE"
        exit 1
fi

leech=${1}
mons=${2}
dano=${3}

echo "scale=5; ${leech}*${fator[${mons}]}*(${dano}*${mons})" | bc
